config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  resources :medicines
  resources :patients do
    resources :logs do
      resources :doses, shallow: true
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/medicine.rb
class Medicine < ApplicationRecord
    has_many :doses
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :set_medicine, only: %i[ show edit update destroy ]

  # GET /medicines or /medicines.json
  def index
    @medicines = Medicine.all
  end

  # GET /medicines/1 or /medicines/1.json
  def show
  end

  # GET /medicines/new
  def new
    @medicine = Medicine.new
  end

  # GET /medicines/1/edit
  def edit
  end

  # POST /medicines or /medicines.json
  def create
    @medicine = Medicine.new(medicine_params)

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, notice: "Medicine was successfully created." }
        format.json { render :show, status: :created, location: @medicine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicines/1 or /medicines/1.json
  def update
    respond_to do |format|
      if @medicine.update(medicine_params)
        format.html { redirect_to @medicine, notice: "Medicine was successfully updated." }
        format.json { render :show, status: :ok, location: @medicine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1 or /medicines/1.json
  def destroy
    @medicine.destroy
    respond_to do |format|
      format.html { redirect_to medicines_url, notice: "Medicine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicine
      @medicine = Medicine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medicine_params
      params.require(:medicine).permit(:generic_name, :brand_name)
    end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/medicines/_form.html.erb
<%= form_with(model: medicine) do |form| %>
<% if medicine.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(medicine.errors.count, "error") %> prohibited this medicine from being saved:</h2>

  <ul>
    <% medicine.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :generic_name %>
  <%= form.text_field :generic_name %>
</div>

<div class="field">
  <%= form.label :brand_name %>
  <%= form.text_field :brand_name %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/medicines/edit.html.erb
<h1>Editing Medicine</h1>

<%= render 'form', medicine: @medicine %>

<%= link_to 'Show', @medicine %> |
<%= link_to 'Back', medicines_path %>

app/views/medicines/index.html.erb
<div class="flex flex-col items-center">
  <h2 class="text-2xl text-gray-800 text-center md:text-left font-bold m-6">
    Medications in system
  </h2>

  <% @medicines.each do |medicine| %>

  <div class="flex justify-between bg-white rounded-full p-4 shadow m-2 ">
    <div>
      <span class="bg-blue-400 text-white rounded-full h-6 px-3 justify-center items-center">
        <%= medicine.generic_name %>
      </span>
      <span class="px-2"><%= medicine.brand_name %></span>
    </div>

    <% if current_user.admin %>
    <div>
      <%= link_to 'Edit', edit_medicine_path(medicine), class: "inline-flex bg-yellow-500 text-white rounded-full h-6 px-6 justify-center items-center" %>
      <span>
        <%= link_to 'Delete', medicine, method: :delete, data: { confirm: 'Are you sure?' }, class: "inline-flex bg-red-500 text-white rounded-full h-6 px-4 justify-center items-center" %>
      </span>
    </div>
    <% end %>
  </div>

  <% end %>
</div>

app/views/medicines/new.html.erb
<h1>New Medicine</h1>

<%= render 'form', medicine: @medicine %>

<%= link_to 'Back', medicines_path %>

app/views/medicines/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Medication</h1>
<p>
  <strong>Generic name:</strong>
  <%= @medicine.generic_name %>
</p>

<p>
  <strong>Brand name:</strong>
  <%= @medicine.brand_name %>
</p>

<%= link_to 'Edit', edit_medicine_path(@medicine) %> |
<%= link_to 'Back', medicines_path %>