config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  resources :medicines
  resources :patients do
    resources :logs do
      resources :doses, shallow: true
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord
    belongs_to :user
    has_many :logs
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: %i[ show edit update destroy ]
  before_action :set_patient, only: %i[ show edit update destroy ]


  # GET /patients or /patients.json
  def index
    if current_user.admin
      @patients = Patient.all
    else
      @patients = current_user.patients
    end
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    # @patient = Patient.new
    @patient = current_user.patients.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = current_user.patients.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    unless current_user.admin
      @patient = current_user.patients.find_by(id: params[:id])
      redirect_to root_path, notice: "You're not authorized to see that!" if @patient.nil?
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :age, :ward_number, :notes, :user_id, :image)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<br>
<br>

<form class="p-14 bg-white max-w-sm mx-auto rounded-xl shadow-xl overflow-hidden p-6 space-y-10">
  <h2 class="text-4xl font-bold text-center text-blue-500">Add New Resident</h2>
  <div>
    <%= form_with(model: patient) do |form| %>
    <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name , class: "bg-gray-100 rounded-lg block p-2 w-full text-lg appearance-none focus:outline-none bg-transparent"%>
    </div>

    <div class="field">
      <%= form.label :age %>
      <%= form.number_field :age , class: "bg-gray-100 rounded-lg block p-2 w-full text-lg appearance-none focus:outline-none bg-transparent"%>
    </div>

    <div class="field">
      <%= form.label :image %>
      <%= form.text_field :image , class: "bg-gray-100 rounded-lg block p-2 w-full text-lg appearance-none focus:outline-none bg-transparent"%>
    </div>

    <div class="field">
      <%= form.label :ward_number %>
      <%= form.text_field :ward_number , class: "bg-gray-100 rounded-lg block p-2 w-full text-lg appearance-none focus:outline-none bg-transparent"%>
    </div>

    <div class="field">
      <%= form.label :notes %>
      <%= form.text_area :notes, class: "bg-gray-100 rounded-lg block p-2 w-full text-lg appearance-none focus:outline-none bg-transparent"%>
    </div>

    <div>
      <%= form.submit class: "py-2 my-4 font-semibold cursor-pointer text-center focus:outline-none transition hover:shadow-lg shadow hover:bg-blue-600 rounded-full text-white bg-blue-500", style: "width: 50%; margin-left:25%;marin-right:25%;"%>
    </div>
    <% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<div class="flex items-center justify-center w-full m-3">
  <%= link_to 'Add a Patient', new_patient_path, class:"btn btn-default content-center" %>
</div>

<% @patients.each do |patient| %>
<div class="flex items-center justify-end w-full m-3">
  <div
    class="container mx-auto p-9 bg-white max-w-sm rounded-2xl overflow-hidden shadow-xl hover:shadow-2xl transition duration-250">
    <img class="rounded-xl" src=<%=patient.image%> alt=image>
    <div class="flex justify-between items-center">
      <div>
        <h1 class="mt-5 text-2xl font-semibold"><%=patient.name%></h1>
        <p class="mt-2">Age: <%=patient.age%></p>
      </div>
      <div>
        <button
          class="text-white text-md font-semibold bg-blue-400 py-2 px-4 rounded-lg shadow-md hover:shadow-lg transition duration-500 transform-gpu hover:scale-110 "><%= link_to 'Go to patient', patient %>
        </button>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/patients/new.html.erb
<%= render 'form', patient: @patient %>

app/views/patients/show.html.erb
<div class="container mx-auto md:grid grid-cols-3 justify-center md:py-20">
  <div class="grid justify-center items-center order-1 col-span-1">
    <img class="lg:h-80 md:h-64 h-40 rounded-full" src=<%=@patient.image%> alt=Image />
    <button
      class="text-white text-md font-semibold bg-blue-400 py-2 px-4 rounded-lg shadow-md hover:shadow-lg transition duration-500 transform-gpu hover:scale-105"
      style="margin-top: 10px"><%= link_to 'Administer Medications', new_patient_log_path(@patient) %>
    </button>
    <button
      class="text-white text-md font-semibold bg-blue-400 py-2 px-4 rounded-lg shadow-md hover:shadow-lg transition duration-500 transform-gpu hover:scale-105"
      style="margin-top: 10px"><%= link_to 'Edit Information', edit_patient_path(@patient)%>
    </button>

  </div>
  <div class="mt-8 md:mt-0 lg:justify-end col-span-2">
    <h1 class="text-4xl text-gray-800 text-center md:text-left font-bold mb-6">Hi, I am <%=@patient.name%></h1>
    <p class="text-xl text-gray-800 text-center md:text-left"><%=@patient.age%> years old</p>
    <br>
    <p class="text-xl text-gray-800 text-center md:text-left">At Ward <%=@patient.ward_number%></p>
    <p>
      <br>
    <p class="text-xl text-gray-800 text-center md:text-left">
      Notes:<br>
      <%=@patient.notes%>
    </p>
    <p>
    </p>



  </div>
</div>
</header>



</footer>
<hr>
<br>
<h2 class="text-2xl text-gray-800 text-center md:text-left font-bold mb-6">Medication Logs</h2>

<% for log in @patient.logs %>
<div class="flex items-center bg-white leading-none text-blue-400 rounded-full p-2 shadow text-teal text-sm"
  style="margin-bottom: 10px; margin-right: 450px">
  <span class="inline-flex bg-blue-400 text-white rounded-full h-6 px-3 justify-center items-center">Medication
    Administered</span>
  <span class="inline-flex px-2"><%= readable_time(log.time_admr)%></span>
</div>
<% end %>