config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  resources :medicines
  resources :patients do
    resources :logs do
      resources :doses, shallow: true
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/log.rb
class Log < ApplicationRecord
    belongs_to :patient
    has_many :doses

    def start_time
        time_admr
    end

    def end_time
        time_admr
    end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :get_patient
  before_action :set_log, only: %i[ show edit update destroy ]

  # GET /logs or /logs.json
  def index
    @logs = @patient.logs
  end

  # GET /logs/1 or /logs/1.json
  def show
    @doses = @log.doses
  end

  # GET /logs/new
  def new
    @log = @patient.logs.build
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs or /logs.json
  def create
    @log = @patient.logs.build(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to patient_log_path(@patient, @log), notice: "Add in the dosages given!" }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1 or /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to patient_logs_path(@patient), notice: "Log was successfully updated." }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1 or /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to patient_logs_path(@patient), notice: "Log was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def get_patient
      @patient = Patient.find(params[:patient_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = @patient.logs.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def log_params
      params.require(:log).permit(:time_admr, dose_attributes:[:amount,:medicine_id])
    end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_calendar.html.erb
<%= month_calendar events: @logs do |date, logs| %>
<%= date %>
<% logs.each do |log| %>
<div>
    <%= link_to readable_time(log.time_admr), patient_log_path(log.patient, log), class:"text-blue-500" %>
</div>
<% end %>
<% end %>

app/views/logs/_form.html.erb
<%= form_with(model: [@patient, log], local: true, html: { class: "p-14 bg-white max-w-sm mx-auto rounded-xl shadow-xl overflow-hidden p-6 space-y-10" })  do |form|%>
<% if log.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

  <ul>
    <% log.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :time_admr, 'Time Administered' %> <br>
  <%= form.datetime_select :time_admr, {}, {class: "border border-gray-300 rounded-full p-2 px-3 my-1"} %>
</div>

<div class="actions">
  <%= form.submit 'Add Log', class: "btn btn-default" %>
</div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Show', [@patient, @log] %> |
<%= link_to 'Back', patient_log_path(@patient) %>

app/views/logs/index.html.erb
<h2 class="pt-4 mb-8 text-4xl font-bold">Your Logs for <%= @patient.name %></h2>

<%= link_to '+ Add Log', new_patient_log_path(@patient), class: "m-2 p-4 font-semibold cursor-pointer text-center focus:outline-none transition hover:shadow-lg shadow hover:bg-blue-600 rounded-full text-white bg-blue-500" %>
<br><br>
<% @logs.each do |log| %>

<div class="flex justify-between p-4 bg-white rounded-full shadow-xl m-2 w-1/2">
  <div><%= log.time_admr %></div>
  <div>
    <%= link_to 'Show', patient_log_path(@patient, log), class: "p-2 px-3 text-white bg-blue-500 rounded-full " %>
    <%= link_to 'Edit', edit_patient_log_path(@patient, log), class: "p-2 px-3 text-white bg-yellow-500 rounded-full " %>
    <%= link_to 'Delete', [@patient, log], method: :delete, data: { confirm: 'Are you sure?' }, class: "p-2 px-3 text-white bg-red-500 rounded-full " %>
  </div>
</div>

<% end %>


<div id="calendar" class="p-8 mt-6 bg-white rounded-sm shadow-xl">
  <h2 class="pt-4 mb-2 text-2xl font-bold">Log Calendar</h2>
  <div id="log-calendar">
    <%= render partial: "calendar", logs: @logs%>
  </div>

</div>

app/views/logs/new.html.erb
<div class="my-5 flex flex-col items-center">
    <h2 class="text-4xl font-bold text-center text-blue-500 m-2">Make a Log</h2>

    <%= render 'form', log: @log %>

    <%= link_to 'Back', patient_logs_path(@patient), class: "btn btn-default m-2" %>
</div>

app/views/logs/show.html.erb
<p>
  <strong>Administrator:</strong>
  <%= current_user.email %>
</p>

<p>
  <strong>Time administered:</strong>
  <%= @log.time_admr %>
</p>

<p>
  <strong>Doses administered</strong> <br />
  <% @doses.each do |d| %>
<div>
  <%= d.amount %> mg of
  <%= d.medicine.generic_name %> (<%= d.medicine.brand_name %>)
  <%= link_to 'Edit', edit_dose_path(d) %>
  <%= link_to 'Destroy', d, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<% end %>
<%= link_to 'New Dose', new_patient_log_dose_path(@patient, @log) %>
</p>

<%= link_to 'Edit', edit_patient_log_path(@patient, @log) %> |
<%= link_to 'See All Logs', patient_logs_path %>